version: "3"
services:
  hydrateme:
      build: .
      ports:
        - "8001:8001"
      volumes:
        - .:/usr/src/app
        - /usr/src/app/node_modules
      environment:
        - NODE_ENV=development
      command: npm run start

networks: 
    docker:
    
volumes:
    jenkins-data:
    jenkins-docker-certs: